application: hatena-diary-reserved-post
version: 1
runtime: python
api_version: 1

handlers:
- url: /post
  script: post.py
  login: admin

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /.*
  script: main.py
